# Generated by Django 5.2.3 on 2025-06-11 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_description', models.TextField(help_text='Description for the Digital Information Portal')),
                ('quick_links_title', models.CharField(default='Quick Links', max_length=100)),
                ('contact_us_title', models.CharField(default='Contact us', max_length=100)),
                ('contact_email', models.CharField(default='contact@company.com', max_length=100)),
                ('contact_phone', models.CharField(default='(977) 9876543210', max_length=50)),
                ('contact_address', models.CharField(default='Kathmandu, Nepal', max_length=255)),
                ('supported_by_title', models.CharField(default='Supported By:', max_length=100)),
                ('supported_by_logo', models.CharField(blank=True, help_text='images/logos/main_logo.png', max_length=255, null=True)),
                ('developed_by_text', models.CharField(default='Developed by', max_length=100)),
                ('developed_by_logo', models.CharField(blank=True, help_text='images/logos/young_minds.png', max_length=255, null=True)),
                ('copyright_text', models.CharField(default='2025 © DAI All Rights Reserved', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('register_button_text', models.CharField(default='Register Now', max_length=50)),
                ('learn_more_button_text', models.CharField(default='Learn More', max_length=50)),
                ('logo_image', models.CharField(help_text='images/logos/main_logo.png', max_length=255)),
                ('logo_alt_text', models.CharField(default='Company Logo', help_text='static/images/logos/secondary_logo.png', max_length=100)),
                ('home_link_text', models.CharField(default='Home', max_length=50)),
                ('about_link_text', models.CharField(default='About', max_length=50)),
                ('schemes_link_text', models.CharField(default='Schemes', max_length=50)),
                ('policies_link_text', models.CharField(default='Policies', max_length=50)),
                ('contact_link_text', models.CharField(default='Contact', max_length=50)),
                ('header_register_button_text', models.CharField(default='Register', max_length=50)),
                ('header_login_button_text', models.CharField(default='login', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
        migrations.CreateModel(
            name='NewsEventsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='See All Events', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'News & Events Section',
            },
        ),
        migrations.CreateModel(
            name='OurServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Our Services Section',
            },
        ),
        migrations.CreateModel(
            name='SMEGuidelinesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'SME Guidelines Section',
            },
        ),
        migrations.CreateModel(
            name='SMEStepsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'SME Steps Section',
            },
        ),
        migrations.CreateModel(
            name='FooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='dashboard.footersection')),
            ],
            options={
                'verbose_name_plural': 'Footer Quick Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text="Path to the image, e.g., 'events/event1.jpg' or a placeholder URL", max_length=255)),
                ('date_location', models.CharField(help_text="e.g., '08-11-2024 Kathmandu'", max_length=100)),
                ('type_text', models.CharField(blank=True, help_text="e.g., 'News', 'Webinar'", max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which the events appear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dashboard.newseventssection')),
            ],
            options={
                'verbose_name_plural': 'News & Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='images/icons/light.svg', max_length=255)),
                ('icon_fallback_text', models.CharField(default='Icon', help_text='Text for image fallback if icon not found', max_length=50)),
                ('status', models.CharField(default='Secure', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which the services appear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dashboard.ourservicessection')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SMEGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Path to the icon, e.g., 'images/icons/light.svg'", max_length=255)),
                ('icon_fallback_text', models.CharField(default='Icon', help_text='Text for image fallback if icon not found', max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which the guidelines appear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='dashboard.smeguidelinessection')),
            ],
            options={
                'verbose_name_plural': 'SME Guidelines',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SMEStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Relative path to the icon within your static files directory, e.g., 'icons/start.png'", max_length=255)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order in which the steps appear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dashboard.smestepssection')),
            ],
            options={
                'verbose_name_plural': 'SME Steps',
                'ordering': ['order'],
            },
        ),
    ]
