# Generated by Django 5.2.3 on 2025-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersection',
            name='portal_logo_alt_text',
            field=models.CharField(blank=True, default='Portal Logo', help_text='Alt text for the portal logo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footersection',
            name='portal_logo_image',
            field=models.CharField(blank=True, help_text="Relative path to the portal logo image in static, e.g., 'logo.png'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='developed_by_logo',
            field=models.CharField(blank=True, help_text="Relative path to developed by logo image within your static files directory, e.g., 'logo/developer.png'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='supported_by_logo',
            field=models.CharField(blank=True, help_text="Relative path to supported by logo image within your static files directory, e.g., 'logo/partner.png'", max_length=255, null=True),
        ),
    ]
