# Generated by Django 5.2.3 on 2025-06-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_footersection_portal_logo_alt_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerquicklink',
            name='footer',
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
        migrations.RemoveField(
            model_name='newsevent',
            name='section',
        ),
        migrations.RemoveField(
            model_name='service',
            name='section',
        ),
        migrations.RemoveField(
            model_name='smeguideline',
            name='section',
        ),
        migrations.RemoveField(
            model_name='smestep',
            name='section',
        ),
        migrations.DeleteModel(
            name='FooterQuickLink',
        ),
        migrations.DeleteModel(
            name='FooterSection',
        ),
        migrations.DeleteModel(
            name='NewsEvent',
        ),
        migrations.DeleteModel(
            name='NewsEventsSection',
        ),
        migrations.DeleteModel(
            name='OurServicesSection',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SMEGuideline',
        ),
        migrations.DeleteModel(
            name='SMEGuidelinesSection',
        ),
        migrations.DeleteModel(
            name='SMEStep',
        ),
        migrations.DeleteModel(
            name='SMEStepsSection',
        ),
    ]
