# Generated by Django 5.2.3 on 2025-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_remove_footerquicklink_footer_delete_landingpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_link', models.CharField(default='Home', max_length=50)),
                ('about_link', models.CharField(default='About', max_length=100)),
                ('schemes_link', models.CharField(default='Schemes', max_length=50)),
                ('policies_link', models.CharField(default='Policies', max_length=50)),
                ('contact_link', models.CharField(default='Contact', max_length=50)),
                ('navbar_register', models.CharField(default='Register', max_length=50)),
                ('navbar_login', models.CharField(default='Login', max_length=50)),
            ],
        ),
    ]
