# Generated by Django 5.2.3 on 2025-06-12 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
        migrations.CreateModel(
            name='BannerButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('order', models.PositiveBigIntegerField(default=0)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='dashboard.banner')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('banner', 'order')},
            },
        ),
    ]
