# Generated by Django 5.2.3 on 2025-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0006_remove_banner_button_link_remove_banner_button_text_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="button1_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="button1_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="button2_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="banner",
            name="button2_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="BannerButton",
        ),
    ]
