# Generated by Django 5.2.3 on 2025-06-13 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_banner_button1_link_banner_button1_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMEStepsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("button_text", models.CharField(default="Get Started", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SMEStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Relative path to the icon within your static files directory, e.g., 'icons/start.png'",
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order in which the steps appear"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="dashboard.smestepssection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
