# Generated by Django 5.2.3 on 2025-06-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_smestepssection_smestep"),
    ]

    operations = [
        migrations.AddField(
            model_name="smestep",
            name="css_left",
            field=models.CharField(
                blank=True,
                help_text="CSS 'left' value (e.g., '15%', '38%', '62%', '85%')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smestep",
            name="css_top",
            field=models.CharField(
                blank=True,
                help_text="CSS 'top' value (e.g., '80%', '60%', '50%', '15%')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smestep",
            name="items_align_class",
            field=models.CharField(
                blank=True,
                default="items-center",
                help_text="Tailwind class for flex items alignment (e.g., 'items-start', 'items-end')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="smestep",
            name="text_align_class",
            field=models.CharField(
                blank=True,
                default="text-center",
                help_text="Tailwind class for text alignment (e.g., 'text-left', 'text-right')",
                max_length=20,
                null=True,
            ),
        ),
    ]
