# Generated by Django 5.2.3 on 2025-06-13 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_smestep_css_left_smestep_css_top_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smestep",
            name="css_left",
        ),
        migrations.RemoveField(
            model_name="smestep",
            name="css_top",
        ),
        migrations.RemoveField(
            model_name="smestep",
            name="items_align_class",
        ),
        migrations.RemoveField(
            model_name="smestep",
            name="text_align_class",
        ),
    ]
