# Generated by Django 5.2.3 on 2025-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_remove_smestep_css_left_remove_smestep_css_top_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smestep",
            name="icon",
            field=models.ImageField(upload_to="static/images/icons/"),
        ),
    ]
