# Generated by Django 5.2.3 on 2025-06-13 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_servicesection_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.RemoveField(
            model_name="service",
            name="order",
        ),
    ]
