# Generated by Django 5.2.3 on 2025-06-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_alter_service_options_remove_service_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.FileField(upload_to="static/images/icons/"),
        ),
    ]
