# Generated by Django 5.2.3 on 2025-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_alter_service_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="service",
            name="section",
        ),
        migrations.AddField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order in which the services appear"
            ),
        ),
    ]
