# Generated by Django 5.2.3 on 2025-06-13 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_alter_service_options_remove_service_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="dashboard.servicesection",
            ),
            preserve_default=False,
        ),
    ]
