# Generated by Django 5.2.3 on 2025-06-13 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0016_service_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smestep",
            name="section",
        ),
        migrations.DeleteModel(
            name="SMEStepsSection",
        ),
    ]
