# Generated by Django 5.2.3 on 2025-06-13 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0017_remove_smestep_section_delete_smestepssection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="section",
        ),
        migrations.DeleteModel(
            name="ServiceSection",
        ),
    ]
