# Generated by Django 5.2.3 on 2025-06-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0018_remove_service_section_delete_servicesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guidelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.FileField(upload_to="static/images/icons/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which the services appear"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
