# Generated by Django 5.2.3 on 2025-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0019_guidelines"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="static/images/newspics/")),
                ("location", models.CharField(max_length=100)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("is_webinar", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
