# Generated by Django 5.2.3 on 2025-06-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0020_newsevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsevent",
            name="event_date",
        ),
        migrations.AddField(
            model_name="newsevent",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="newsevent",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
