# Generated by Django 5.2.3 on 2025-06-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0021_remove_newsevent_event_date_newsevent_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("location", "Location"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
    ]
