# Generated by Django 5.2.3 on 2025-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0023_quicklinks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navbar",
            name="about_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="contact_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="home_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="navbar_login",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="navbar_register",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="policies_link",
        ),
        migrations.RemoveField(
            model_name="navbar",
            name="schemes_link",
        ),
        migrations.AddField(
            model_name="navbar",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="navbar",
            name="url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
