# Generated by Django 5.2.3 on 2025-06-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0024_remove_navbar_about_link_remove_navbar_contact_link_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(upload_to="static/images/icons/")),
                ("url", models.URLField()),
            ],
        ),
    ]
