# Generated by Django 5.2.3 on 2025-06-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0025_sociallinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallinks",
            name="icon",
            field=models.FileField(upload_to="static/images/icons/"),
        ),
    ]
