# Generated by Django 5.2.3 on 2025-06-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0027_notice_alter_navbar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/notices/"),
        ),
        migrations.AddField(
            model_name="notice",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="static/notices"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
