# Generated by Django 5.2.3 on 2025-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0028_notice_image_notice_pdf_alter_notice_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["popup_order", "-created_at"]},
        ),
        migrations.AddField(
            model_name="notice",
            name="is_popup",
            field=models.BooleanField(
                default=False, help_text="Check to show this notice as a pop up"
            ),
        ),
        migrations.AddField(
            model_name="notice",
            name="popup_order",
            field=models.PositiveIntegerField(
                blank=True, help_text="order of popup display if multiple", null=True
            ),
        ),
    ]
