# Generated by Django 5.2.3 on 2025-06-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0029_alter_notice_options_notice_is_popup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="tag",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="subtitle",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
