# Generated by Django 5.2.3 on 2025-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0031_cmspage_menuitem_delete_navbar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cmspage",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="cmspage",
            name="meta_title",
        ),
        migrations.AddField(
            model_name="cmspage",
            name="meta_tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags for SEO", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
