# Generated by Django 5.2.3 on 2025-06-17 10:47

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0032_remove_cmspage_meta_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dashboard.menuitem",
            ),
        ),
    ]
