# Generated by Django 5.2.3 on 2025-06-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0034_menuitem_level_menuitem_lft_menuitem_rght_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="level",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dashboard.menuitem",
            ),
        ),
    ]
