# Generated by Django 5.2.3 on 2025-06-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0035_remove_menuitem_level_remove_menuitem_lft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cms_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.cmspage",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="module",
            field=models.CharField(
                blank=True,
                help_text="Optional module for internal pages",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
