# Generated by Django 5.2.3 on 2025-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0036_menuitem_cms_id_menuitem_module_alter_cmspage_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="module",
            field=models.CharField(
                blank=True,
                help_text="Named URL for internal pages",
                max_length=100,
                null=True,
            ),
        ),
    ]
