# Generated by Django 5.2.3 on 2025-06-18 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0037_alter_menuitem_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="link",
        ),
    ]
