# Generated by Django 5.2.3 on 2025-06-18 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0038_remove_menuitem_link"),
    ]

    operations = []
