# Generated by Django 5.2.3 on 2025-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0039_auto_20250618_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
