# Generated by Django 5.2.3 on 2025-06-30 05:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0040_banner_is_active_notice_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Infos",
            },
        ),
        migrations.AlterModelOptions(
            name="quicklinks",
            options={
                "verbose_name": "Quick Link",
                "verbose_name_plural": "Quick Links",
            },
        ),
        migrations.AlterModelOptions(
            name="sociallinks",
            options={
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
            },
        ),
        migrations.AlterField(
            model_name="cmspage",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
