# Generated by Django 5.2.3 on 2025-06-30 05:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0041_alter_contactinfo_options_alter_quicklinks_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
