# Generated by Django 5.2.3 on 2025-06-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0042_alter_cmspage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
