# Generated by Django 5.2.3 on 2025-06-30 09:07

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0043_alter_cmspage_content_alter_newsevent_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspage",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
