# Generated by Django 5.2.3 on 2025-07-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0044_alter_cmspage_content_alter_newsevent_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidelines",
            name="icon",
            field=models.FileField(upload_to="uploads/icons/guidelines/"),
        ),
        migrations.AlterField(
            model_name="newsevent",
            name="image",
            field=models.ImageField(upload_to="uploads/news/images"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/notices/images/"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/notices/pdfs/"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.FileField(upload_to="uploads/icons/service/"),
        ),
        migrations.AlterField(
            model_name="smestep",
            name="icon",
            field=models.ImageField(upload_to="uploads/icons/sme_steps/"),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="icon",
            field=models.FileField(upload_to="uploads/icons/sociallinks/"),
        ),
    ]
