# Generated by Django 5.2.3 on 2025-07-01 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0045_alter_guidelines_icon_alter_newsevent_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ["order"],
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
        migrations.AlterModelOptions(
            name="guidelines",
            options={
                "ordering": ["order"],
                "verbose_name": "Guidelines",
                "verbose_name_plural": "Guidelines",
            },
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={
                "ordering": ["order"],
                "verbose_name": "Menu Item",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.AlterModelOptions(
            name="newsevent",
            options={
                "verbose_name": "News Event",
                "verbose_name_plural": "News Events",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["order"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="smestep",
            options={
                "ordering": ["order"],
                "verbose_name": "SME Step",
                "verbose_name_plural": "SME Steps",
            },
        ),
    ]
