# Generated by Django 5.2.3 on 2025-07-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0046_alter_banner_options_alter_guidelines_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsevent",
            name="is_webinar",
        ),
        migrations.AddField(
            model_name="newsevent",
            name="category",
            field=models.CharField(
                choices=[("news", "News"), ("webinar", "Webinar"), ("event", "Event")],
                default="news",
                max_length=20,
            ),
        ),
    ]
